### PR TITLE
First run-through of chapter 3

### PR DESCRIPTION
**Pull request by med-ayssar**

### CODE REVIEW

**Comment by jougs** [comment]
I'm afraid my changes heavily collide with yours. If you did not change a lot, I think it's better to just accept my changes and discard yours.

**Comment by med-ayssar** [comment]
> I'm afraid my changes heavily collide with yours. If you did not change a lot, I think it's better to just accept my changes and discard yours.

I just removed what you have told me regarding the `\emph` command, and I resized the figures in the third chapter. Better to keep your changes in the third chapter and accept mine for the remaining parts.

**Comment by jougs** [comment]
I also have resized your figures and removed the `\emph`s. So I think it is safe to take my version.

**Comment by med-ayssar** [comment]
> I also have resized your figures and removed the `\emph`s. So I think it is safe to take my version.

You just changed one file, so I think it is pretty safe to accept your changes then.

**Comment by jougs** [comment]
Fixed.

**Comment by med-ayssar** [comment]
Once you lift the Draft state, I will merge it!

**Comment by jougs** [comment]
I can't.

> This pull request is still a work in progress
Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can mark a draft pull request as ready for review.

**Pull request merged**
